// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bvhvfoaktwrodispylrv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ2aHZmb2FrdHdyb2Rpc3B5bHJ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNTA3MzIsImV4cCI6MjA3MzkyNjczMn0.D81pEpe0AAp8AL_2FT7qRUdsYd0dmCCkIaB_NavSbO4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});